// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cmFMvhGdKx5qIPjzvWYgCgLcyeMk_nA',
    appId: '1:707440341592:android:40b561c194fa995b92502d',
    messagingSenderId: '707440341592',
    projectId: 'child-safety-app-dbd4d',
    databaseURL: 'https://child-safety-app-dbd4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'child-safety-app-dbd4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR6y8a6Ny6wlx2jDUpOiqG44bklYhpfuI',
    appId: '1:707440341592:ios:dcf7dfcc147b6b2c92502d',
    messagingSenderId: '707440341592',
    projectId: 'child-safety-app-dbd4d',
    databaseURL: 'https://child-safety-app-dbd4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'child-safety-app-dbd4d.firebasestorage.app',
    iosClientId: '707440341592-v4d1sm1mqph2r9gbs68nbt8dim30mobh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp2',
  );
}
